[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/server/*"
  to = "/"
  status = 404

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
